### ISSUE TITLE
error on composer update

### ISSUE THREAD

**Issue by parabol** [TerrePorter/LaravelFrameworkLoader#1]
Hi,

im getting this error  when i try to install your package.

[Composer\Repository\InvalidRepositoryException]                                                                                                       
  No valid composer.json was found in any branch or tag of https://github.com/TerrePorter/LaravelFrameworkLoader.git, could not load a package from it.

**Comment by TerrePorter** [comment]
I've added a composer.json file, not sure how that did not get included. Give that a try and let me know if it works, or if you have other problems.
